name: ğŸ¦€ Push Event Workflow ğŸ 

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v4
      
    - name : Install Python Packages 
      run : pip install -r requirements.txt
      
    - name : Run hamiltonian tests
      run : pytest tests/hamiltonian.py

    - name : Run information tests
      run : pytest tests/information.py
